#!/bin/sh
# Resolve all dependencies that the application requires to run.

# Stop on errors
set -e

cd "$(realpath "$(dirname "$0")/..")"

echo "Installing development dependencies..."
uv pip install \
  -e . \
  -r requirements.txt \
  --upgrade \
  --config-settings editable_mode=compat
